EveBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^captcha/', include('captcha.urls')),

]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login/action/$', views.login_action, name='login_action'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/action/$', views.register_action, name="register_action"),
    url(r'^forget/$', views.forget, name='forget'),

]

blog/models.py
from django.db import models
from captcha.fields import CaptchaField

# Create your models here.


# 用户注册/登录信息
class User(models.Model):
    email = models.EmailField(blank=False)
    password = models.CharField(blank=False, max_length=100)

blog/forms.py
from django import forms
from captcha.fields import CaptchaField


# 验证码
class RegisterForm(forms.Form):
    captcha = CaptchaField(error_messages={"invalid": "验证码错误"})

blog/views.py
from django.shortcuts import render, HttpResponse

from blog.forms import RegisterForm
from django import forms
from .models import User
from captcha.fields import CaptchaField, CaptchaStore
from captcha.helpers import captcha_image_url


# Create your views here.

# 主页面
def index(request):
    return render(request, 'blog/index.html')


# 注册表单
class UserFormRegister(forms.Form):
    email = forms.EmailField(max_length=100)
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


# 登录表单
class UserFormLogin(forms.Form):
    email = forms.EmailField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


# 登录页面
def login(request):
    user_formlogin = UserFormLogin()
    return render(request, 'blog/login.html', {'user_formlogin': user_formlogin})


# 登录操作页面
def login_action(request):
    # # 刷新验证码
    # if request.GET.get('newsn') == '1':
    #     csn = CaptchaStore.generate_key()
    #     cimageurl = captcha_image_url(csn)
    #     return HttpResponse(cimageurl)

    if request.method == 'POST':
        user_formlogin = UserFormLogin(request.POST)
        if user_formlogin.is_valid():
            # 获取表单信息
            email = user_formlogin.cleaned_data['email']
            password = user_formlogin.cleaned_data['password']
            errors = []
            # 获得的表单数据与数据库进行比较
            user_result = User.objects.filter(email__exact=email, password__exact=password)

            if user_result:
                # 如果比较成功，则跳转主页index.html
                response = render(request, 'blog/login_success.html', locals())
                response.set_cookie('email', email, 3600)
                return response
            else:
                # 如果比较失败，则仍在login.html
                return render(request, 'blog/login.html', {'errors': '该用户名不存在'}, locals())

    else:
        user_formlogin = UserFormLogin()
    return render(request, 'blog/login.html', {'user_formlogin': user_formlogin}, locals())


# 注册页面
def register(request):
    user_formregister = UserFormRegister()
    return render(request, 'blog/register.html', {'user_formregister': user_formregister}, locals())


# 注册操作页面
def register_action(request):
    if request.method == 'POST':
        user_formregister = UserFormRegister(request.POST)
        if user_formregister.is_valid():
            # 获取表单数据
            email = user_formregister.cleaned_data['email']
            password = user_formregister.cleaned_data['password1']
            password1 = user_formregister.cleaned_data['password1']
            password2 = user_formregister.cleaned_data['password2']

            if User.objects.filter(email__exact=email):
                return render(request, 'blog/register.html', {'errors': '该用户名已存在'})

            if password2 != password1:
                return render(request, 'blog/register.html', {'errors': '两次输入密码不一致'})

            # 添加到数据库中
            user = User.objects.create(email=email, password=password)
            user.save()
            # 返回注册成功页面
            return render(request, 'blog/login_success.html', {'email': email})

    else:
        user_formregister = UserFormRegister()
    return render(request, 'blog/register.html', {'user_formregister': user_formregister})


# 忘记密码页面
def forget(request):
    return render(request, 'blog/forget.html')

blog/templates/blog/forget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/global.css">
</head>
<body>

{#header#}
<div class="header">
  <div class="main">
    <a class="logo" href="/" title="Fly">Fly社区</a>
    <div class="nav">
      <a class="nav-this" href="jie/index.html">
        <i class="iconfont icon-wenda"></i>交流
      </a>
      <a href="/case/2017/" target="_blank">
          <i class="iconfont icon-iconmingxinganli" style="top: 20px"></i>案例

      </a>
      <a href="http://www.layui.com/" target="_blank">
        <i class="iconfont icon-ui"></i>框架
      </a>
    </div>

    <div class="nav-user">
      <!-- 未登入状态 -->
      <a class="unlogin" href="{% url 'blog:login' %}"><i class="iconfont icon-touxiang"></i></a>
      <span>
          <a href="{% url 'blog:login' %}">登入</a>
          <a href="{% url 'blog:register' %}">注册</a>
      </span>

    </div>
  </div>
</div>

{#main form#}
<div class layui-clear>
    <div class="fly-panel fly-panel-user" pad20>
        <div class="layui-tab layui-tab-brief" lay-filter="user">
            <ul class="layui-tab-title">
                <li class="layui-this">找回密码</li>

            </ul>
            <div class="layui-form layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
                <div class="layui-tab-item layui-show">
                    <div class="layui-form layui-form-pane">
                        <form method="post">
                            {% csrf_token %}
                            <div class="layui-form-item">
                                <label for="L_email" class="layui-form-label">邮箱</label>
                                <div class="layui-input-inline">
                                    <input type="text" id="L_email" name="email" required lay-verify="required" placeholder="您注册时的邮箱" autocomplete="off" class="layui-input">
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <label for="L_vercode" class="layui-form-label">人类验证</label>
                                <div class="layui-input-inline">
                                    <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="请回答后面的问题" autocomplete="off" class="layui-input">
                                </div>
                                <div class="layui-form-mid">
                                    <span style="color: #cc0000;">Node.js 诞生于哪一年？</span>
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <button class="layui-btn" lay-filter="*" lay-submit>提交</button>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


</div>



<div class="footer">
    <p>
        <a href="http://fly.layui.com/">Fly社区</a>"2017 @"
        <a href="http://www.layui.com/">layui.com</a>
    </p>
</div>

</body>
</html>

blog/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/global.css">
</head>
<body>

{#header#}
<div class="header">
  <div class="main">
    <a class="logo" href="/" title="Fly">Fly社区</a>
    <div class="nav">
      <a class="nav-this" href="jie/index.html">
        <i class="iconfont icon-wenda"></i>交流
      </a>
      <a href="/case/2017/" target="_blank">
          <i class="iconfont icon-iconmingxinganli" style="top: 20px"></i>案例

      </a>
      <a href="http://www.layui.com/" target="_blank">
        <i class="iconfont icon-ui"></i>框架
      </a>
    </div>

    <div class="nav-user">
      <!-- 未登入状态 -->
      <a class="unlogin" href="{% url 'blog:login' %}"><i class="iconfont icon-touxiang"></i></a>
      <span>
          <a href="{% url 'blog:login' %}">登入</a>
          <a href="{% url 'blog:register' %}">注册</a>
      </span>

    </div>
  </div>
</div>

{#main form#}
<div class layui-clear>
    <div class="fly-panel fly-panel-user" pad20>
        <div class="layui-tab layui-tab-brief" lay-filter="user">
            <ul class="layui-tab-title">
                <li class="layui-this">登入</li>
                <li><a href="{% url 'blog:register' %}">注册</a></li>
            </ul>
            <div class="layui-form layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
                <div class="layui-tab-item layui-show">
                    <div class="layui-form layui-form-pane">
                        <form action="{% url 'blog:login_action' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="layui-form-item">
                                <label for="L_email" class="layui-form-label">邮箱</label>
                                <div class="layui-input-inline">
                                    <input type="text" id="L_email" name="email" required lay-verify="required" placeholder="邮箱" autocomplete="off" class="layui-input">
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <label for="L_pass" class="layui-form-label">密码</label>
                                <div class="layui-input-inline">
                                    <input type="password" id="L_pass" name="password" required lay-verify="required" placeholder="密码" autocomplete="off" class="layui-input">
                                </div>
                            </div>


                            <div class="layui-form-item captcha1 {% if user_formlogin.errors.captcha %} errorput{% endif %}">
                                <label for="L_vercode" class="layui-form-label">验证码</label>
                                <div class="layui-input-inline">
                                    {#                                   <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="验证码" autocomplete="off" class="layui-input">#}
                                    <span style="color: #cc0000;">{{ user_formlogin.captcha }}</span>

                                </div>
                                <div class="layui-form-mid">
                                    <button class='js-captcha-refresh'>刷新验证码</button>
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <button class="layui-btn" lay-filter="*" lay-submit>立即登录</button>
                                <span style="padding-left: 20px;"><a href="{% url 'blog:forget' %}">忘记密码?</a></span>
                            </div>

                            {{ errors }}

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


</div>



<div class="footer">
    <p>
        <a href="http://fly.layui.com/">Fly社区</a>"2017 @"
        <a href="http://www.layui.com/">layui.com</a>
    </p>
</div>

<script>
$('.js-captcha-refresh').click(function(){
    $user_formlogin = $(this).parents('user_formlogin');

    $.getJSON($(this).data('url'), {}, function(json) {
        // This should update your captcha image src and captcha hidden input
    });

    return false;
});
</script>

</body>
</html>

blog/templates/blog/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout page</title>
</head>
<body>

</body>
</html>

blog/templates/blog/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/global.css">
</head>
<body>

{#header#}
<div class="header">
  <div class="main">
    <a class="logo" href="/" title="Fly">Fly社区</a>
    <div class="nav">
      <a class="nav-this" href="jie/index.html">
        <i class="iconfont icon-wenda"></i>交流
      </a>
      <a href="/case/2017/" target="_blank">
          <i class="iconfont icon-iconmingxinganli" style="top: 20px"></i>案例

      </a>
      <a href="http://www.layui.com/" target="_blank">
        <i class="iconfont icon-ui"></i>框架
      </a>
    </div>

    <div class="nav-user">
      <!-- 未登入状态 -->
      <a class="unlogin" href="{% url 'blog:login' %}"><i class="iconfont icon-touxiang"></i></a>
      <span>
          <a href="{% url 'blog:login' %}">登入</a>
          <a href="{% url 'blog:register' %}">注册</a>
      </span>

    </div>
  </div>
</div>

{#main form#}
<div class layui-clear>
    <div class="fly-panel fly-panel-user" pad20>
        <div class="layui-tab layui-tab-brief" lay-filter="user">
            <ul class="layui-tab-title">
                <li><a href="{% url 'blog:login' %}">登入</a></li>
                <li class="layui-this">注册</li>

            </ul>
            <div class="layui-form layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
                <div class="layui-tab-item layui-show">
                    <div class="layui-form layui-form-pane">
                        <form action="{% url 'blog:register_action' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="layui-form-item">
                                <label for="L_email" class="layui-form-label">邮箱</label>
                                <div class="layui-input-inline">
                                    <input type="text" id="L_email" name="email" required lay-verify="required" placeholder="将会成为您唯一的登入名" autocomplete="off" class="layui-input">
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <label for="L_pass" class="layui-form-label">密码</label>
                                <div class="layui-input-inline">
                                    <input type="password" id="L_pass" name="password1" required lay-verify="required" placeholder="6到16个字符" autocomplete="off" class="layui-input">
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <label for="L_repass" class="layui-form-label">确认密码</label>
                                <div class="layui-input-inline">
                                    <input type="password" id="L_repass" name="password2" required lay-verify="required" autocomplete="off" class="layui-input">
                                </div>
                            </div>


                            <div class="layui-form-item">
                                <label for="L_vercode" class="layui-form-label">验证码</label>
                                <div class="layui-input-inline">
{#                                    <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="请回答后面的问题" autocomplete="off" class="layui-input">#}
                                    <span style="color: #cc0000;">{{ user_formregister.captcha }}</span>
                                </div>
{#                                <div class="layui-form-mid">#}
{#                                    <span style="color: #cc0000;">{{ reg_form.captcha }}</span>#}
{#                                </div>#}
                            </div>



                            <div class="layui-form-item">
                                <button class="layui-btn" lay-filter="*" lay-submit>立即注册</button>
                            </div>
                            {{ errors }}

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


</div>



<div class="footer">
    <p>
        <a href="http://fly.layui.com/">Fly社区</a>"2017 @"
        <a href="http://www.layui.com/">layui.com</a>
    </p>
</div>

</body>
</html>